# Generated by Django 4.2.9 on 2024-10-23 10:35

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Mã nghề')),
                ('name', models.CharField(max_length=100, verbose_name='Tên nghề')),
                ('name_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tên tiếng Anh')),
                ('symbol', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tên viết tắt')),
                ('ser_num', models.IntegerField(blank=True, null=True, verbose_name='Số thứ tự')),
                ('note', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ghi chú')),
            ],
            options={
                'verbose_name': 'Nghề',
                'verbose_name_plural': 'Nghề',
                'db_table': 'career',
            },
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='Mã lớp')),
                ('code_number', models.CharField(max_length=50, verbose_name='Mã lớp (số)')),
                ('classname', models.CharField(max_length=100, verbose_name='Tên lớp')),
                ('teacher', models.CharField(max_length=255, verbose_name='Giáo viên chủ nhiệm')),
                ('qty', models.IntegerField(default=1, verbose_name='Sĩ số')),
                ('training_fac', models.CharField(max_length=255, verbose_name='Cơ sở đào tạo')),
                ('course', models.CharField(max_length=255, verbose_name='Khóa học')),
                ('major', models.CharField(max_length=255, verbose_name='Chuyên ngành')),
                ('career', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.career', verbose_name='Nghề')),
            ],
            options={
                'verbose_name': 'Lớp học',
                'verbose_name_plural': 'Lớp học',
                'db_table': 'classroom',
            },
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='Mã ngành')),
                ('name', models.CharField(max_length=100, verbose_name='Tên ngành')),
                ('enroll_code', models.CharField(max_length=10, verbose_name='Mã ngành tuyển sinh')),
                ('department', models.CharField(max_length=255, verbose_name='Khoa')),
                ('name_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tên tiếng Anh')),
            ],
            options={
                'verbose_name': 'Chuyên ngành',
                'verbose_name_plural': 'Chuyên ngành',
                'db_table': 'major',
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, verbose_name='Mã tỉnh')),
                ('name', models.CharField(max_length=100, verbose_name='Tên tỉnh')),
                ('name_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tên tiếng Anh')),
            ],
            options={
                'verbose_name': 'Tỉnh thành phố',
                'verbose_name_plural': 'Tỉnh thành phố',
                'db_table': 'province',
            },
        ),
        migrations.CreateModel(
            name='SchoolYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=2024, verbose_name='Năm học')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Niên khóa')),
                ('from_date', models.DateField(verbose_name='Từ ngày')),
                ('to_date', models.DateField(verbose_name='Đến ngày')),
                ('name_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='Tên tiếng Anh')),
                ('code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Mã năm học')),
            ],
            options={
                'verbose_name': 'Năm học',
                'verbose_name_plural': 'Năm học',
                'db_table': 'school_year',
            },
        ),
        migrations.CreateModel(
            name='SubjectType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Mã loại môn học')),
                ('name', models.CharField(max_length=100, verbose_name='Tên loại môn học')),
                ('ser_num', models.IntegerField(blank=True, null=True, verbose_name='Số thứ tự')),
                ('note', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ghi chú')),
            ],
            options={
                'verbose_name': 'Loại môn học',
                'verbose_name_plural': 'Loại môn học',
                'db_table': 'subject_type',
            },
        ),
        migrations.CreateModel(
            name='TrainingSys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Mã hệ đào tạo')),
                ('name', models.CharField(max_length=100, verbose_name='Tên hệ đào tạo')),
                ('ser_num', models.IntegerField(blank=True, null=True, verbose_name='Số thứ tự')),
                ('note', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ghi chú')),
            ],
            options={
                'verbose_name': 'Hệ đào tạo',
                'verbose_name_plural': 'Hệ đào tạo',
                'db_table': 'training_sys',
            },
        ),
        migrations.CreateModel(
            name='TrainingType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, verbose_name='Mã loại hình đào tạo')),
                ('name', models.CharField(max_length=100, verbose_name='Tên loại hình đào tạo')),
                ('ser_num', models.IntegerField(blank=True, null=True, verbose_name='Số thứ tự')),
                ('note', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ghi chú')),
                ('type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Hình thức')),
                ('name_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tên tiếng anh')),
                ('is_visible', models.BooleanField(blank=True, null=True, verbose_name='Trạng thái hiển thị')),
            ],
            options={
                'verbose_name': 'Loại hình đào tạo',
                'verbose_name_plural': 'Loại hình đào tạo',
                'db_table': 'training_type',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=200, verbose_name='Mã môn học')),
                ('name', models.CharField(max_length=200, verbose_name='Tên môn học')),
                ('name_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tên tiếng Anh')),
                ('department', models.CharField(max_length=255, verbose_name='Khoa')),
                ('sub_group', models.CharField(max_length=255, verbose_name='Tổ bộ môn')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.subjecttype', verbose_name='Loại môn học')),
            ],
            options={
                'verbose_name': 'Môn học',
                'verbose_name_plural': 'Môn học',
                'db_table': 'subject',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.CharField(max_length=20, unique=True, verbose_name='Mã sinh viên')),
                ('lastname', models.CharField(max_length=50, verbose_name='Họ và tên đệm')),
                ('firstname', models.CharField(max_length=20, verbose_name='Tên')),
                ('gender', models.IntegerField(choices=[(1, 'Male'), (2, 'Female')], default=1, verbose_name='Giới tính')),
                ('dob', models.DateField(blank=True, null=True, verbose_name='Ngày sinh')),
                ('phone', models.CharField(blank=True, max_length=100, null=True, verbose_name='Số điện thoại')),
                ('training_fac', models.CharField(max_length=255, verbose_name='Cơ sở đào tạo')),
                ('course', models.CharField(max_length=255, verbose_name='Khóa học')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='Email')),
                ('status', models.IntegerField(default=1, verbose_name='Trạng thái sinh viên')),
                ('acc', models.CharField(blank=True, max_length=100, null=True, verbose_name='Số tài khoản')),
                ('pwd', models.CharField(max_length=100, verbose_name='Mật khẩu đăng nhập')),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.classroom', verbose_name='Lớp học')),
                ('major', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.major', verbose_name='Chuyên ngành')),
                ('pob', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.province', verbose_name='Nơi sinh')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.trainingtype', verbose_name='Loại hình đào tạo')),
            ],
            options={
                'verbose_name': 'Quản lý sinh viên',
                'verbose_name_plural': 'Quản lý sinh viên',
                'db_table': 'students',
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ser_number', models.IntegerField(default=1, verbose_name='Số thứ tự')),
                ('code', models.CharField(max_length=50, verbose_name='Mã học kỳ')),
                ('name', models.CharField(max_length=50, verbose_name='Tên học kỳ')),
                ('is_active', models.BooleanField(default=True, verbose_name='Trạng thái kích hoạt')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Trạng thái hiển thị')),
                ('week_number', models.IntegerField(default=8, verbose_name='Số tuần học')),
                ('from_month', models.IntegerField(default=1, verbose_name='Từ tháng')),
                ('to_month', models.IntegerField(default=1, verbose_name='Đến tháng')),
                ('from_date', models.DateField(verbose_name='Từ ngày')),
                ('to_date', models.DateField(verbose_name='Đến ngày')),
                ('name_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='Tên tiếng Anh')),
                ('school_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.schoolyear', verbose_name='Năm học')),
            ],
            options={
                'verbose_name': 'Học kỳ',
                'verbose_name_plural': 'Học kỳ',
                'db_table': 'semester',
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='Mã khung chương trình')),
                ('name', models.TextField(verbose_name='Tên khung chương trình')),
                ('training_fac', models.CharField(max_length=255, verbose_name='Cơ sở đào tạo')),
                ('course', models.CharField(max_length=255, verbose_name='Khóa học')),
                ('type_of_career', models.CharField(max_length=255, verbose_name='Loại nghề')),
                ('training_lang', models.CharField(max_length=255, verbose_name='Ngôn ngữ đào tạo')),
                ('career', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.career', verbose_name='Nghề')),
                ('major', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.major', verbose_name='Chuyên ngành')),
                ('training_sys', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.trainingsys', verbose_name='Hệ đào tạo')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.trainingtype', verbose_name='Loại hình đào tạo')),
            ],
            options={
                'verbose_name': 'Khung chương trình',
                'verbose_name_plural': 'Khung chương trình',
                'db_table': 'program',
            },
        ),
        migrations.AddField(
            model_name='classroom',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.trainingtype', verbose_name='Loại hình đào tạo'),
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('staff', 'staff'), ('manager', 'manager')], default='staff', max_length=15)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
