from .attendance import * 
from .classrooms import * 
from .custom_user import * 
from .enrollments import * 
from .exam import *
from .grades import * 
from .semester import * 
from .student import * 
from .subject import * 
from .timetables import *